services:
  product_app:
    build: ./product_service
    expose:
      - "5000"
    depends_on:
      - shop_db
    environment:
      - FLASK_ENV=development

  order_app:
    build: ./order_service
    expose:
      - "5000"
    depends_on:
      - shop_db
    environment:
      - FLASK_ENV=development

  shop_db:
    image: "redis:alpine"
    container_name: shop_shared_redis
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - product_app
      - order_app
