events { worker_connections 1024; }

http {
    # Load Balancing Pools
    upstream product_cluster {
        server product_app:5000;
    }

    upstream order_cluster {
        server order_app:5000;
    }

    server {
        listen 80;

        # Route to Product Service
        location /product/ {
            proxy_pass http://product_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route to Order Service
        location /order/ {
            proxy_pass http://order_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
